[build-dependencies]
bindgen = "0.71.1"

[package]
build = "build.rs"
name = "LabJackUD_rust"
authors = ["Callum Welsh <callumwelsh@princeton.edu>"]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
